Change MasterChef to work with (any) non-mintable ERC20 token.
ltonetwork/uniswap-farming pull request #3
Opened 2020-11-02 11:54 UTC by jasny

Remove contracts for (mintable) Sashimi token.
Remove contract for migrating Uniswap LP to Sashimi.

2020-11-02 12:17 UTC, sven4ask requested changes

2020-11-02 12:17 UTC, sven4ask commented on contracts/MasterChef.sol
> +        sashimi.transfer(_to, _amount);
This token has been removed, but still used? Should be replaced by something else.

2020-11-03 03:13 UTC, jasny commented
TODO: write tests

2020-11-09 13:30 UTC, sven4ask approved these changes

2020-11-10 14:17 UTC, merged